
"""
SDC check function
This function will perform all output comparison after the benchmark executed
the function MUST have the name sdc_check and two parameters
this must have 2 parameters which will be set in FI execution time
You can perform any comparison inside this script
golden_output_path : golden data path
inj_output_path : output generated by injection execution
"""


def sdc_check(golden_output_path, inj_output_path):
    golden_data = open(golden_output_path).readlines()
    inj_data = open(inj_output_path).readlines()

    # Compare output
    if len(golden_data) != len(inj_data):
        return False

    for g, f in zip(golden_data, inj_data):
        if g != f:
            return False
    return True
