CC=gcc -g 
CC_FLAGS=-fopenmp  -lm

ts = $(shell /bin/date "+%Y-%m-%d")
folder="hotspot-knl-files-"$(ts)

all: gen_bin gen_data

gen_bin: hotspot.c
	$(CC) $(CC_FLAGS) hotspot.c -o hotspot

gen_data: gen_bin
	./hotspot 1024 1024 1000 272 temp_1024 power_1024 gold_1024
	mkdir -p $(folder)
	mv hotspot gold_1024 $(folder)
	cp temp_1024 power_1024 $(folder)
	@echo "All Done"
	@echo "Gold and executables copy are stored in $(folder)"
